on:
  push:
    branches:
      - main
    paths:
      - .docker/**/*
      - .github/workflows/run-tests.yml
      - bin/**/*
      - package.json
      - package-lock.json
      - src/**/*
      - tests/**/*
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ./.docker/client/Dockerfile
      volumes:
        - .:/app
    services:
      server:
        image: ./.docker/server/Dockerfile
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
